document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("");
document.writeln("	<!-- 引用自己的库 -->");
document.writeln("	<link rel=\'stylesheet\' href=\'resource/css/cite.css\'>");
document.writeln("	<script src=\'resource/js/cite.js\'></script>");
document.writeln("	<link rel=\'shortcut icon\' href=\'img/eeg-icon.svg\'>");
document.writeln("");
document.writeln("	<!-- 3.6.0最新 -->");
document.writeln("	<script src=\'https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\'></script>");
document.writeln("");
document.writeln("	<!-- bootstrap 4.6.0 -->");
document.writeln("	<link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\'>");
document.writeln("	<script src=\'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("	<!-- tocbot 4.12.3 -->");
document.writeln("	<link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/npm/tocbot@4.12.3/dist/tocbot.css\'>");
document.writeln("	<script src=\'https://cdn.jsdelivr.net/npm/tocbot@4.12.3/dist/tocbot.min.js\'></script>");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<nav class=\'navbar navbar-expand-lg navbar-light site-header\' style=\'background-color: #B4C6E7;\'>");
document.writeln("	<button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarsExample08\'");
document.writeln("		aria-controls=\'navbarsExample08\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("		<span class=\'navbar-toggler-icon\'></span>");
document.writeln("	</button>");
document.writeln("");
document.writeln("	<div class=\'collapse navbar-collapse justify-content-md-center\' id=\'navbarsExample08\'>");
document.writeln("		<ul class=\'navbar-nav\'>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'index.html\' aria-label=\'回到主页\'>");
document.writeln("					<img src=\'resource/img/nwpu.png\'");
document.writeln("						style=\'width:28px; height:28px; border-radius:100%; overflow:hidden;\' />");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'research.html\'>研究领域</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'member.html\'>人员组成</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'resource.html\'>资源</a>");
document.writeln("			</li>");
document.writeln("			<!-- <li class=\'nav-item dropdown\'>");
document.writeln("				<a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'dropdown08\' data-toggle=\'dropdown\'");
document.writeln("					aria-expanded=\'false\'>Dropdown</a>");
document.writeln("				<div class=\'dropdown-menu\' aria-labelledby=\'dropdown08\'>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Action</a>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Another action</a>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Something else here</a>");
document.writeln("				</div>");
document.writeln("			</li> -->");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</nav>");
document.writeln("");