document.writeln("<nav class=\'navbar navbar-expand-lg navbar-light site-header\' style=\'background-color: #B4C6E7;\'>");
document.writeln("	<button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarsExample08\'");
document.writeln("		aria-controls=\'navbarsExample08\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("		<span class=\'navbar-toggler-icon\'></span>");
document.writeln("	</button>");
document.writeln("");
document.writeln("	<div class=\'collapse navbar-collapse justify-content-md-center\' id=\'navbarsExample08\'>");
document.writeln("		<ul class=\'navbar-nav\'>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'index.html\' aria-label=\'回到主页\'>");
document.writeln("					<img src=\'resource/img/nwpu.png\'");
document.writeln("						style=\'width:28px; height:28px; border-radius:100%; overflow:hidden;\' />");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'research.html\'>研究领域</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'member.html\'>人员组成</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-item btn btn-outline-primary\' >");
document.writeln("				<a class=\'nav-link\' href=\'resource.html\'>资源</a>");
document.writeln("			</li>");
document.writeln("			<!-- <li class=\'nav-item dropdown\'>");
document.writeln("				<a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'dropdown08\' data-toggle=\'dropdown\'");
document.writeln("					aria-expanded=\'false\'>Dropdown</a>");
document.writeln("				<div class=\'dropdown-menu\' aria-labelledby=\'dropdown08\'>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Action</a>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Another action</a>");
document.writeln("					<a class=\'dropdown-item\' href=\'#\'>Something else here</a>");
document.writeln("				</div>");
document.writeln("			</li> -->");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</nav>");
document.writeln("");